/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CommunityInvitationDetails,
  InvitationDetails,
  InvitationResponseRequest,
  InvitePayload,
  Message,
  SendInvitationsPayload,
} from '.././schemas';

/**
 * @summary Invite Registered Users
 */
export const communitiesApiInvitationInviteRegisteredUsers = (
  communityId: number,
  invitePayload: InvitePayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Message>> => {
  return axios.post(
    `http://localhost:8000/api/communities/communities/${communityId}/invite-users`,
    invitePayload,
    options
  );
};

export const getCommunitiesApiInvitationInviteRegisteredUsersMutationOptions = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>,
    TError,
    { communityId: number; data: InvitePayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>,
  TError,
  { communityId: number; data: InvitePayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>,
    { communityId: number; data: InvitePayload }
  > = (props) => {
    const { communityId, data } = props ?? {};

    return communitiesApiInvitationInviteRegisteredUsers(communityId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunitiesApiInvitationInviteRegisteredUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>
>;
export type CommunitiesApiInvitationInviteRegisteredUsersMutationBody = InvitePayload;
export type CommunitiesApiInvitationInviteRegisteredUsersMutationError = AxiosError<Message>;

/**
 * @summary Invite Registered Users
 */
export const useCommunitiesApiInvitationInviteRegisteredUsers = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>,
    TError,
    { communityId: number; data: InvitePayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof communitiesApiInvitationInviteRegisteredUsers>>,
  TError,
  { communityId: number; data: InvitePayload },
  TContext
> => {
  const mutationOptions = getCommunitiesApiInvitationInviteRegisteredUsersMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Respond To Invitation
 */
export const communitiesApiInvitationRespondToInvitation = (
  invitationId: number,
  invitationResponseRequest: InvitationResponseRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Message>> => {
  return axios.post(
    `http://localhost:8000/api/communities/invitations/${invitationId}/respond`,
    invitationResponseRequest,
    options
  );
};

export const getCommunitiesApiInvitationRespondToInvitationMutationOptions = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>,
    TError,
    { invitationId: number; data: InvitationResponseRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>,
  TError,
  { invitationId: number; data: InvitationResponseRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>,
    { invitationId: number; data: InvitationResponseRequest }
  > = (props) => {
    const { invitationId, data } = props ?? {};

    return communitiesApiInvitationRespondToInvitation(invitationId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunitiesApiInvitationRespondToInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>
>;
export type CommunitiesApiInvitationRespondToInvitationMutationBody = InvitationResponseRequest;
export type CommunitiesApiInvitationRespondToInvitationMutationError = AxiosError<Message>;

/**
 * @summary Respond To Invitation
 */
export const useCommunitiesApiInvitationRespondToInvitation = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>,
    TError,
    { invitationId: number; data: InvitationResponseRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToInvitation>>,
  TError,
  { invitationId: number; data: InvitationResponseRequest },
  TContext
> => {
  const mutationOptions = getCommunitiesApiInvitationRespondToInvitationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Send Invitations To Unregistered Users
 */
export const communitiesApiInvitationSendInvitationsToUnregisteredUsers = (
  communityId: number,
  sendInvitationsPayload: SendInvitationsPayload,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Message>> => {
  return axios.post(
    `http://localhost:8000/api/communities/communities/${communityId}/send-invitations`,
    sendInvitationsPayload,
    options
  );
};

export const getCommunitiesApiInvitationSendInvitationsToUnregisteredUsersMutationOptions = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>,
    TError,
    { communityId: number; data: SendInvitationsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>,
  TError,
  { communityId: number; data: SendInvitationsPayload },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>,
    { communityId: number; data: SendInvitationsPayload }
  > = (props) => {
    const { communityId, data } = props ?? {};

    return communitiesApiInvitationSendInvitationsToUnregisteredUsers(
      communityId,
      data,
      axiosOptions
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunitiesApiInvitationSendInvitationsToUnregisteredUsersMutationResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>
>;
export type CommunitiesApiInvitationSendInvitationsToUnregisteredUsersMutationBody =
  SendInvitationsPayload;
export type CommunitiesApiInvitationSendInvitationsToUnregisteredUsersMutationError =
  AxiosError<Message>;

/**
 * @summary Send Invitations To Unregistered Users
 */
export const useCommunitiesApiInvitationSendInvitationsToUnregisteredUsers = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>,
    TError,
    { communityId: number; data: SendInvitationsPayload },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof communitiesApiInvitationSendInvitationsToUnregisteredUsers>>,
  TError,
  { communityId: number; data: SendInvitationsPayload },
  TContext
> => {
  const mutationOptions =
    getCommunitiesApiInvitationSendInvitationsToUnregisteredUsersMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Respond To Email Invitation
 */
export const communitiesApiInvitationRespondToEmailInvitation = (
  token: string,
  invitationResponseRequest: InvitationResponseRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Message>> => {
  return axios.post(
    `http://localhost:8000/api/communities/invitations/respond/${token}`,
    invitationResponseRequest,
    options
  );
};

export const getCommunitiesApiInvitationRespondToEmailInvitationMutationOptions = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>,
    TError,
    { token: string; data: InvitationResponseRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>,
  TError,
  { token: string; data: InvitationResponseRequest },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>,
    { token: string; data: InvitationResponseRequest }
  > = (props) => {
    const { token, data } = props ?? {};

    return communitiesApiInvitationRespondToEmailInvitation(token, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunitiesApiInvitationRespondToEmailInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>
>;
export type CommunitiesApiInvitationRespondToEmailInvitationMutationBody =
  InvitationResponseRequest;
export type CommunitiesApiInvitationRespondToEmailInvitationMutationError = AxiosError<Message>;

/**
 * @summary Respond To Email Invitation
 */
export const useCommunitiesApiInvitationRespondToEmailInvitation = <
  TError = AxiosError<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>,
    TError,
    { token: string; data: InvitationResponseRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationResult<
  Awaited<ReturnType<typeof communitiesApiInvitationRespondToEmailInvitation>>,
  TError,
  { token: string; data: InvitationResponseRequest },
  TContext
> => {
  const mutationOptions =
    getCommunitiesApiInvitationRespondToEmailInvitationMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get Community Invitations
 */
export const communitiesApiInvitationGetCommunityInvitations = (
  communityId: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<InvitationDetails[]>> => {
  return axios.get(`http://localhost:8000/api/communities/${communityId}/invitations`, options);
};

export const getCommunitiesApiInvitationGetCommunityInvitationsQueryKey = (communityId: number) => {
  return [`http://localhost:8000/api/communities/${communityId}/invitations`] as const;
};

export const getCommunitiesApiInvitationGetCommunityInvitationsQueryOptions = <
  TData = Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>,
  TError = AxiosError<Message>,
>(
  communityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCommunitiesApiInvitationGetCommunityInvitationsQueryKey(communityId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>
  > = ({ signal }) =>
    communitiesApiInvitationGetCommunityInvitations(communityId, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!communityId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CommunitiesApiInvitationGetCommunityInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>
>;
export type CommunitiesApiInvitationGetCommunityInvitationsQueryError = AxiosError<Message>;

/**
 * @summary Get Community Invitations
 */
export const useCommunitiesApiInvitationGetCommunityInvitations = <
  TData = Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>,
  TError = AxiosError<Message>,
>(
  communityId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitations>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCommunitiesApiInvitationGetCommunityInvitationsQueryOptions(
    communityId,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get Community Invitation Details
 */
export const communitiesApiInvitationGetCommunityInvitationDetails = (
  communityId: number,
  invitationId: number,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<CommunityInvitationDetails>> => {
  return axios.get(
    `http://localhost:8000/api/communities/${communityId}/invitation-details/${invitationId}`,
    options
  );
};

export const getCommunitiesApiInvitationGetCommunityInvitationDetailsQueryKey = (
  communityId: number,
  invitationId: number
) => {
  return [
    `http://localhost:8000/api/communities/${communityId}/invitation-details/${invitationId}`,
  ] as const;
};

export const getCommunitiesApiInvitationGetCommunityInvitationDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>,
  TError = AxiosError<Message>,
>(
  communityId: number,
  invitationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCommunitiesApiInvitationGetCommunityInvitationDetailsQueryKey(communityId, invitationId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>
  > = ({ signal }) =>
    communitiesApiInvitationGetCommunityInvitationDetails(communityId, invitationId, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(communityId && invitationId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CommunitiesApiInvitationGetCommunityInvitationDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>
>;
export type CommunitiesApiInvitationGetCommunityInvitationDetailsQueryError = AxiosError<Message>;

/**
 * @summary Get Community Invitation Details
 */
export const useCommunitiesApiInvitationGetCommunityInvitationDetails = <
  TData = Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>,
  TError = AxiosError<Message>,
>(
  communityId: number,
  invitationId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communitiesApiInvitationGetCommunityInvitationDetails>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCommunitiesApiInvitationGetCommunityInvitationDetailsQueryOptions(
    communityId,
    invitationId,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
