/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from '.././custom-instance';
import type { BodyType, ErrorType } from '.././custom-instance';
import type {
  BookmarkSchema,
  FavoriteItemSchema,
  Message,
  NotificationSchema,
  PaginatedArticlesListResponse,
  PaginatedCommunities,
  UserArticleSchema,
  UserCommunitySchema,
  UserDetails,
  UserPostSchema,
  UserStats,
  UsersApiGetNotificationsParams,
  UsersApiListMyArticlesParams,
  UsersApiListMyCommunitiesParams,
  UsersApiUpdateUserBody,
} from '.././schemas';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Get Me
 */
export const usersApiGetMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserDetails>({ url: `/api/users/me`, method: 'GET', signal }, options);
};

export const getUsersApiGetMeQueryKey = () => {
  return [`/api/users/me`] as const;
};

export const getUsersApiGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMe>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMe>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMe>>> = ({ signal }) =>
    usersApiGetMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof usersApiGetMe>>>;
export type UsersApiGetMeQueryError = ErrorType<Message>;

/**
 * @summary Get Me
 */
export const useUsersApiGetMe = <
  TData = Awaited<ReturnType<typeof usersApiGetMe>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMe>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Update User
 */
export const usersApiUpdateUser = (
  usersApiUpdateUserBody: BodyType<UsersApiUpdateUserBody>,
  options?: SecondParameter<typeof customInstance>
) => {
  const formData = new FormData();
  if (usersApiUpdateUserBody.profile_image !== undefined) {
    formData.append('profile_image', usersApiUpdateUserBody.profile_image);
  }
  formData.append('payload', JSON.stringify(usersApiUpdateUserBody.payload));

  return customInstance<UserDetails>(
    {
      url: `/api/users/me`,
      method: 'PUT',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options
  );
};

export const getUsersApiUpdateUserMutationOptions = <
  TError = ErrorType<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersApiUpdateUser>>,
    TError,
    { data: BodyType<UsersApiUpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersApiUpdateUser>>,
  TError,
  { data: BodyType<UsersApiUpdateUserBody> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersApiUpdateUser>>,
    { data: BodyType<UsersApiUpdateUserBody> }
  > = (props) => {
    const { data } = props ?? {};

    return usersApiUpdateUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersApiUpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersApiUpdateUser>>
>;
export type UsersApiUpdateUserMutationBody = BodyType<UsersApiUpdateUserBody>;
export type UsersApiUpdateUserMutationError = ErrorType<Message>;

/**
 * @summary Update User
 */
export const useUsersApiUpdateUser = <TError = ErrorType<Message>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersApiUpdateUser>>,
    TError,
    { data: BodyType<UsersApiUpdateUserBody> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersApiUpdateUser>>,
  TError,
  { data: BodyType<UsersApiUpdateUserBody> },
  TContext
> => {
  const mutationOptions = getUsersApiUpdateUserMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get User Stats
 */
export const usersApiGetUserStats = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserStats>({ url: `/api/users/me/stats`, method: 'GET', signal }, options);
};

export const getUsersApiGetUserStatsQueryKey = () => {
  return [`/api/users/me/stats`] as const;
};

export const getUsersApiGetUserStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetUserStats>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetUserStats>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetUserStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetUserStats>>> = ({ signal }) =>
    usersApiGetUserStats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetUserStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetUserStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetUserStats>>
>;
export type UsersApiGetUserStatsQueryError = ErrorType<Message>;

/**
 * @summary Get User Stats
 */
export const useUsersApiGetUserStats = <
  TData = Awaited<ReturnType<typeof usersApiGetUserStats>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetUserStats>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetUserStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get Contributed Articles
 */
export const usersApiGetMyArticles = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserArticleSchema[]>(
    { url: `/api/users/contributed-articles`, method: 'GET', signal },
    options
  );
};

export const getUsersApiGetMyArticlesQueryKey = () => {
  return [`/api/users/contributed-articles`] as const;
};

export const getUsersApiGetMyArticlesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMyArticles>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyArticles>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMyArticlesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMyArticles>>> = ({ signal }) =>
    usersApiGetMyArticles(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMyArticles>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMyArticlesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetMyArticles>>
>;
export type UsersApiGetMyArticlesQueryError = ErrorType<Message>;

/**
 * @summary Get Contributed Articles
 */
export const useUsersApiGetMyArticles = <
  TData = Awaited<ReturnType<typeof usersApiGetMyArticles>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyArticles>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMyArticlesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get My Articles
 */
export const usersApiListMyArticles = (
  params?: UsersApiListMyArticlesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedArticlesListResponse>(
    { url: `/api/users/my-articles`, method: 'GET', params, signal },
    options
  );
};

export const getUsersApiListMyArticlesQueryKey = (params?: UsersApiListMyArticlesParams) => {
  return [`/api/users/my-articles`, ...(params ? [params] : [])] as const;
};

export const getUsersApiListMyArticlesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiListMyArticles>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiListMyArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiListMyArticles>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiListMyArticlesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiListMyArticles>>> = ({ signal }) =>
    usersApiListMyArticles(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiListMyArticles>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiListMyArticlesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiListMyArticles>>
>;
export type UsersApiListMyArticlesQueryError = ErrorType<Message>;

/**
 * @summary Get My Articles
 */
export const useUsersApiListMyArticles = <
  TData = Awaited<ReturnType<typeof usersApiListMyArticles>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiListMyArticlesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiListMyArticles>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiListMyArticlesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get My Communities
 */
export const usersApiListMyCommunities = (
  params?: UsersApiListMyCommunitiesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<PaginatedCommunities>(
    { url: `/api/users/my-communities`, method: 'GET', params, signal },
    options
  );
};

export const getUsersApiListMyCommunitiesQueryKey = (params?: UsersApiListMyCommunitiesParams) => {
  return [`/api/users/my-communities`, ...(params ? [params] : [])] as const;
};

export const getUsersApiListMyCommunitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiListMyCommunities>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiListMyCommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiListMyCommunities>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiListMyCommunitiesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiListMyCommunities>>> = ({
    signal,
  }) => usersApiListMyCommunities(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiListMyCommunities>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiListMyCommunitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiListMyCommunities>>
>;
export type UsersApiListMyCommunitiesQueryError = ErrorType<Message>;

/**
 * @summary Get My Communities
 */
export const useUsersApiListMyCommunities = <
  TData = Awaited<ReturnType<typeof usersApiListMyCommunities>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiListMyCommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiListMyCommunities>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiListMyCommunitiesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get Contributed Communities
 */
export const usersApiGetMyCommunities = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserCommunitySchema[]>(
    { url: `/api/users/contributed-communities`, method: 'GET', signal },
    options
  );
};

export const getUsersApiGetMyCommunitiesQueryKey = () => {
  return [`/api/users/contributed-communities`] as const;
};

export const getUsersApiGetMyCommunitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMyCommunities>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyCommunities>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMyCommunitiesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMyCommunities>>> = ({
    signal,
  }) => usersApiGetMyCommunities(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMyCommunities>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMyCommunitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetMyCommunities>>
>;
export type UsersApiGetMyCommunitiesQueryError = ErrorType<Message>;

/**
 * @summary Get Contributed Communities
 */
export const useUsersApiGetMyCommunities = <
  TData = Awaited<ReturnType<typeof usersApiGetMyCommunities>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyCommunities>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMyCommunitiesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get My Posts
 */
export const usersApiGetMyPosts = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<UserPostSchema[]>(
    { url: `/api/users/contributed-posts`, method: 'GET', signal },
    options
  );
};

export const getUsersApiGetMyPostsQueryKey = () => {
  return [`/api/users/contributed-posts`] as const;
};

export const getUsersApiGetMyPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMyPosts>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyPosts>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMyPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMyPosts>>> = ({ signal }) =>
    usersApiGetMyPosts(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMyPosts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMyPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetMyPosts>>
>;
export type UsersApiGetMyPostsQueryError = ErrorType<Message>;

/**
 * @summary Get My Posts
 */
export const useUsersApiGetMyPosts = <
  TData = Awaited<ReturnType<typeof usersApiGetMyPosts>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyPosts>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMyPostsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get My Favorites
 */
export const usersApiGetMyFavorites = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<FavoriteItemSchema[]>(
    { url: `/api/users/my-favorites`, method: 'GET', signal },
    options
  );
};

export const getUsersApiGetMyFavoritesQueryKey = () => {
  return [`/api/users/my-favorites`] as const;
};

export const getUsersApiGetMyFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMyFavorites>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyFavorites>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMyFavoritesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMyFavorites>>> = ({ signal }) =>
    usersApiGetMyFavorites(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMyFavorites>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMyFavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetMyFavorites>>
>;
export type UsersApiGetMyFavoritesQueryError = ErrorType<Message>;

/**
 * @summary Get My Favorites
 */
export const useUsersApiGetMyFavorites = <
  TData = Awaited<ReturnType<typeof usersApiGetMyFavorites>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyFavorites>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMyFavoritesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get My Bookmarks
 */
export const usersApiGetMyBookmarks = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<BookmarkSchema[]>(
    { url: `/api/users/bookmarks`, method: 'GET', signal },
    options
  );
};

export const getUsersApiGetMyBookmarksQueryKey = () => {
  return [`/api/users/bookmarks`] as const;
};

export const getUsersApiGetMyBookmarksQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetMyBookmarks>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyBookmarks>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetMyBookmarksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetMyBookmarks>>> = ({ signal }) =>
    usersApiGetMyBookmarks(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetMyBookmarks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetMyBookmarksQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetMyBookmarks>>
>;
export type UsersApiGetMyBookmarksQueryError = ErrorType<Message>;

/**
 * @summary Get My Bookmarks
 */
export const useUsersApiGetMyBookmarks = <
  TData = Awaited<ReturnType<typeof usersApiGetMyBookmarks>>,
  TError = ErrorType<Message>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof usersApiGetMyBookmarks>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetMyBookmarksQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get Notifications
 */
export const usersApiGetNotifications = (
  params?: UsersApiGetNotificationsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<NotificationSchema[]>(
    { url: `/api/users/notifications`, method: 'GET', params, signal },
    options
  );
};

export const getUsersApiGetNotificationsQueryKey = (params?: UsersApiGetNotificationsParams) => {
  return [`/api/users/notifications`, ...(params ? [params] : [])] as const;
};

export const getUsersApiGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof usersApiGetNotifications>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiGetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiGetNotifications>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersApiGetNotificationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof usersApiGetNotifications>>> = ({
    signal,
  }) => usersApiGetNotifications(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersApiGetNotifications>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersApiGetNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersApiGetNotifications>>
>;
export type UsersApiGetNotificationsQueryError = ErrorType<Message>;

/**
 * @summary Get Notifications
 */
export const useUsersApiGetNotifications = <
  TData = Awaited<ReturnType<typeof usersApiGetNotifications>>,
  TError = ErrorType<Message>,
>(
  params?: UsersApiGetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof usersApiGetNotifications>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getUsersApiGetNotificationsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Mark Notification As Read
 */
export const usersApiMarkNotificationAsRead = (
  notificationId: number,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Message>(
    { url: `/api/users/notifications/${notificationId}/mark-as-read`, method: 'POST' },
    options
  );
};

export const getUsersApiMarkNotificationAsReadMutationOptions = <
  TError = ErrorType<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>,
    TError,
    { notificationId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>,
  TError,
  { notificationId: number },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>,
    { notificationId: number }
  > = (props) => {
    const { notificationId } = props ?? {};

    return usersApiMarkNotificationAsRead(notificationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersApiMarkNotificationAsReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>
>;

export type UsersApiMarkNotificationAsReadMutationError = ErrorType<Message>;

/**
 * @summary Mark Notification As Read
 */
export const useUsersApiMarkNotificationAsRead = <
  TError = ErrorType<Message>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>,
    TError,
    { notificationId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof usersApiMarkNotificationAsRead>>,
  TError,
  { notificationId: number },
  TContext
> => {
  const mutationOptions = getUsersApiMarkNotificationAsReadMutationOptions(options);

  return useMutation(mutationOptions);
};
