api:
  dashboard: false
  debug: false

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: scicommons_proxy

certificatesResolvers:
  cloudflare:
    acme:
      email: suresh.krishna@mcgill.ca
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
