/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type ArticlesApiCreateArticleBody = {
  abstract: string;
  authors: string;
  image_file?: Blob;
  keywords: string;
  pdf_file?: Blob;
  submission_type: string;
  title: string;
};
