/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleUpdateSchema } from './articleUpdateSchema';

export type ArticlesApiUpdateArticleBody = {
  details: ArticleUpdateSchema;
  image_file?: Blob;
  pdf_file?: Blob;
};
