/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleCreateSchema } from './articleCreateSchema';

export type ArticlesApiCreateArticleBody = {
  details: ArticleCreateSchema;
  image_file?: Blob;
  pdf_files: Blob[];
};
