/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleCreateDetailsSubmissionType } from './articleCreateDetailsSubmissionType';
import type { Tag } from './tag';

export interface ArticleCreateDetails {
  abstract: string;
  authors: Tag[];
  keywords: Tag[];
  submission_type: ArticleCreateDetailsSubmissionType;
  title: string;
}
