/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleSchemaImage } from './articleSchemaImage';
import type { ArticleSchemaPdfFile } from './articleSchemaPdfFile';
import type { PaginatedReviewSchema } from './paginatedReviewSchema';

export interface ArticleSchema {
  abstract: string;
  authors: string;
  id: number;
  image?: ArticleSchemaImage;
  keywords: string;
  pdf_file?: ArticleSchemaPdfFile;
  reviews: PaginatedReviewSchema;
  slug: string;
  submission_type: string;
  submitter: number;
  title: string;
}
