/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleCreateDetailsArticleLink } from './articleCreateDetailsArticleLink';
import type { ArticleCreateDetailsCommunityName } from './articleCreateDetailsCommunityName';
import type { ArticleCreateDetailsPdfLink } from './articleCreateDetailsPdfLink';
import type { ArticleCreateDetailsSubmissionType } from './articleCreateDetailsSubmissionType';
import type { Tag } from './tag';

export interface ArticleCreateDetails {
  abstract: string;
  article_link?: ArticleCreateDetailsArticleLink;
  authors: Tag[];
  community_name?: ArticleCreateDetailsCommunityName;
  pdf_link?: ArticleCreateDetailsPdfLink;
  submission_type: ArticleCreateDetailsSubmissionType;
  title: string;
}
