/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleOut } from './articleOut';
import type { ArticleStatusSchemaPublishedAt } from './articleStatusSchemaPublishedAt';
import type { ArticleStatusSchemaSubmittedAt } from './articleStatusSchemaSubmittedAt';
import type { AssessorSchema } from './assessorSchema';

export interface ArticleStatusSchema {
  article: ArticleOut;
  assessors: AssessorSchema[];
  published_at: ArticleStatusSchemaPublishedAt;
  status: string;
  submitted_at: ArticleStatusSchemaSubmittedAt;
}
