/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type ArticlesApiGetRelevantArticlesFilterType =
  (typeof ArticlesApiGetRelevantArticlesFilterType)[keyof typeof ArticlesApiGetRelevantArticlesFilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArticlesApiGetRelevantArticlesFilterType = {
  popular: 'popular',
  recent: 'recent',
  relevant: 'relevant',
} as const;
