/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type ArticleCreateDetailsSubmissionType =
  (typeof ArticleCreateDetailsSubmissionType)[keyof typeof ArticleCreateDetailsSubmissionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArticleCreateDetailsSubmissionType = {
  Public: 'Public',
  Private: 'Private',
} as const;
