/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum for filtering bookmarks by type.
 */
export type BookmarkFilterTypeEnum =
  (typeof BookmarkFilterTypeEnum)[keyof typeof BookmarkFilterTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BookmarkFilterTypeEnum = {
  article: 'article',
  community: 'community',
  all: 'all',
} as const;
