/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ID of the parent comment if it's a reply
 */
export type CommentCreateSchemaParentId = number | null;
