/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface CommunityInvitationDetails {
  description: string;
  name: string;
  num_members: number;
  profile_pic_url: string;
}
