/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleCommunityDetails } from './articleCommunityDetails';
import type { CommunityArticleOutModeratorId } from './communityArticleOutModeratorId';
import type { CommunityArticleOutPublishedAt } from './communityArticleOutPublishedAt';
import type { CommunityArticleOutStatus } from './communityArticleOutStatus';

export interface CommunityArticleOut {
  community: ArticleCommunityDetails;
  id: number;
  moderator_id?: CommunityArticleOutModeratorId;
  published_at: CommunityArticleOutPublishedAt;
  reviewer_ids?: number[];
  status: CommunityArticleOutStatus;
  submitted_at: string;
}
