/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommentModelOutId } from './commentModelOutId';

export interface CommentModelOut {
  author: number;
  content: string;
  created_at: string;
  id?: CommentModelOutId;
  is_deleted?: boolean;
  replies?: unknown[];
}
