/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CommunityType = (typeof CommunityType)[keyof typeof CommunityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunityType = {
  public: 'public',
  hidden: 'hidden',
  private: 'private',
} as const;
