/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityArticleStatsResponseCommunityName } from './communityArticleStatsResponseCommunityName';
import type { DateCount } from './dateCount';
import type { ReviewExcerpt } from './reviewExcerpt';

export interface CommunityArticleStatsResponse {
  average_rating: number;
  community_name: CommunityArticleStatsResponseCommunityName;
  discussions: number;
  has_user_reviewed?: boolean;
  likes: number;
  likes_over_time: DateCount[];
  recent_reviews: ReviewExcerpt[];
  reviews_count: number;
  reviews_over_time: DateCount[];
  submission_date: string;
  submitter: string;
  title: string;
}
