/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CommunitiesArticlesApiManageArticleAction =
  (typeof CommunitiesArticlesApiManageArticleAction)[keyof typeof CommunitiesArticlesApiManageArticleAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunitiesArticlesApiManageArticleAction = {
  approve: 'approve',
  reject: 'reject',
  publish: 'publish',
} as const;
