/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityListOutCreatedAt } from './communityListOutCreatedAt';
import type { CommunityListOutIsBookmarked } from './communityListOutIsBookmarked';
import type { CommunityListOutOrg } from './communityListOutOrg';
import type { CommunityListOutRole } from './communityListOutRole';
import type { CommunityType } from './communityType';

export interface CommunityListOut {
  created_at?: CommunityListOutCreatedAt;
  description: string;
  id: number;
  is_bookmarked?: CommunityListOutIsBookmarked;
  name: string;
  num_members: number;
  num_published_articles: number;
  org?: CommunityListOutOrg;
  role?: CommunityListOutRole;
  slug: string;
  type: CommunityType;
}
