/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatsResponseArticleSubmissionTrendsItem } from './communityStatsResponseArticleSubmissionTrendsItem';
import type { CommunityStatsResponseMemberGrowthItem } from './communityStatsResponseMemberGrowthItem';
import type { RecentArticleSchema } from './recentArticleSchema';

export interface CommunityStatsResponse {
  article_submission_trends: CommunityStatsResponseArticleSubmissionTrendsItem[];
  articles_published: number;
  description: string;
  member_growth: CommunityStatsResponseMemberGrowthItem[];
  name: string;
  new_articles_this_week: number;
  new_members_this_week: number;
  new_published_articles_this_week: number;
  recently_published_articles: RecentArticleSchema[];
  total_articles: number;
  total_discussions: number;
  total_members: number;
  total_reviews: number;
}
