/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CommunitiesApiJoinManageJoinRequestAction =
  (typeof CommunitiesApiJoinManageJoinRequestAction)[keyof typeof CommunitiesApiJoinManageJoinRequestAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunitiesApiJoinManageJoinRequestAction = {
  approve: 'approve',
  reject: 'reject',
} as const;
