/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleStatus } from './articleStatus';

export type CommunitiesArticlesApiListCommunityArticlesByStatusParams = {
  status?: ArticleStatus | null;
  submitted_after?: string | null;
  submitted_before?: string | null;
  page?: number;
  size?: number;
  sort_by?: string;
  sort_order?: string;
};
