/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionArticleOut } from './subscriptionArticleOut';

export interface CommunitySubscriptionOut {
  articles: SubscriptionArticleOut[];
  community_id: number;
  community_name: string;
  is_admin: boolean;
}
