/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CommunityRoleFilter = typeof CommunityRoleFilter[keyof typeof CommunityRoleFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunityRoleFilter = {
  admin: 'admin',
  moderator: 'moderator',
  reviewer: 'reviewer',
  member: 'member',
} as const;
