/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommentOutId } from './commentOutId';
import type { UserStats } from './userStats';

export interface CommentOut {
  author: UserStats;
  content: string;
  created_at: string;
  id?: CommentOutId;
  is_author?: boolean;
  replies: CommentOut[];
  upvotes: number;
}
