/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type CommunitiesApiListCommunitiesParams = {
  search?: string | null;
  sort?: string | null;
  page?: number;
  per_page?: number;
};
