/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePostSchemaCitedArticleId } from './createPostSchemaCitedArticleId';
import type { CreatePostSchemaCitedUrl } from './createPostSchemaCitedUrl';

export interface CreatePostSchema {
  cited_article_id?: CreatePostSchemaCitedArticleId;
  cited_url?: CreatePostSchemaCitedUrl;
  content: string;
  title: string;
}
