/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityType } from './communityType';
import type { CreateCommunityDetailsCommunitySettings } from './createCommunityDetailsCommunitySettings';

export interface CreateCommunityDetails {
  community_settings?: CreateCommunityDetailsCommunitySettings;
  description: string;
  name: string;
  type: CommunityType;
}
