/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityType } from './communityType';

export interface CreateCommunityDetails {
  description: string;
  name: string;
  tags: string[];
  type: CommunityType;
  community_settings?: string;
}
