/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { DiscussionOutDeletedAt } from './discussionOutDeletedAt';
import type { DiscussionOutId } from './discussionOutId';
import type { UserStats } from './userStats';

export interface DiscussionOut {
  anonymous_name?: string;
  article_id: number;
  comments_count?: number;
  content: string;
  created_at: string;
  deleted_at?: DiscussionOutDeletedAt;
  id?: DiscussionOutId;
  is_author?: boolean;
  /** @maxLength 200 */
  topic: string;
  updated_at: string;
  user: UserStats;
}
