/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entity types that can have flags attached.
This is the single source of truth — the EntityFlag model stores any string,
validation happens at the API layer via this enum.
 */
export type EntityType = typeof EntityType[keyof typeof EntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityType = {
  discussion: 'discussion',
  comment: 'comment',
  notification: 'notification',
  review: 'review',
  article: 'article',
} as const;
