/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entity types that can have flags attached.
Keep in sync with UserFlag.VALID_ENTITY_TYPES in articles/models.py

- discussion: A discussion thread on an article
- comment: A comment or reply within a discussion
- notification: A user notification

Future entity types (add here and in UserFlag.VALID_ENTITY_TYPES when implemented):
- article: An article
- review: A review on an article
 */
export type EntityType = typeof EntityType[keyof typeof EntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntityType = {
  discussion: 'discussion',
  comment: 'comment',
  notification: 'notification',
} as const;
