/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { FeedPreferenceOutUpdatedAt } from './feedPreferenceOutUpdatedAt';

/**
 * Current feed preferences for the logged-in user.
 */
export interface FeedPreferenceOut {
  authors?: string[];
  has_saved_preferences?: boolean;
  keywords?: string[];
  similar_to?: string[];
  topics?: string[];
  updated_at?: FeedPreferenceOutUpdatedAt;
}
