/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Payload sent by the feed-preferences form (and by template imports).
 */
export interface FeedPreferenceIn {
  authors?: string[];
  keywords?: string[];
  similar_to?: string[];
  topics?: string[];
}
