/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleStatus } from './articleStatus';

export type FiltersStatus = ArticleStatus | null;
