/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type FilterType = (typeof FilterType)[keyof typeof FilterType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterType = {
  popular: 'popular',
  recent: 'recent',
  relevant: 'relevant',
} as const;
