/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { EntityType } from './entityType';
import type { FlagType } from './flagType';

/**
 * Request schema for flag operations (GET/POST/DELETE).

All operations use the same request format for consistency.
 */
export interface FlagRequestIn {
  entity_ids: number[];
  entity_type: EntityType;
  flag_type: FlagType;
}
