/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { InviteSchemaEmail } from './inviteSchemaEmail';
import type { InviteSchemaUsername } from './inviteSchemaUsername';

export interface InviteSchema {
  email?: InviteSchemaEmail;
  username?: InviteSchemaUsername;
}
