/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { InvitationSchemaEmail } from './invitationSchemaEmail';
import type { InvitationSchemaUsername } from './invitationSchemaUsername';

export interface InvitationSchema {
  email: InvitationSchemaEmail;
  id: number;
  invited_at: string;
  status: string;
  username: InvitationSchemaUsername;
}
