/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type InvitationResponseRequestAction =
  (typeof InvitationResponseRequestAction)[keyof typeof InvitationResponseRequestAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvitationResponseRequestAction = {
  accept: 'accept',
  reject: 'reject',
} as const;
