/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type LikeDislikeSchemaVote =
  (typeof LikeDislikeSchemaVote)[keyof typeof LikeDislikeSchemaVote];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LikeDislikeSchemaVote = {
  NUMBER_1: 1,
  NUMBER_MINUS_1: -1,
} as const;
