/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface LogInUserSchemaOut {
  email: string;
  first_name: string;
  id: number;
  last_name: string;
  username: string;
}
