/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type MyappFlagsApiGetFlagsEntityType = typeof MyappFlagsApiGetFlagsEntityType[keyof typeof MyappFlagsApiGetFlagsEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyappFlagsApiGetFlagsEntityType = {
  discussion: 'discussion',
  comment: 'comment',
  notification: 'notification',
  review: 'review',
} as const;
