/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type MyappFlagsApiGetFlagsFlagType = typeof MyappFlagsApiGetFlagsFlagType[keyof typeof MyappFlagsApiGetFlagsFlagType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyappFlagsApiGetFlagsFlagType = {
  unread: 'unread',
} as const;
