/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationSchemaContent } from './notificationSchemaContent';
import type { NotificationSchemaExpiresAt } from './notificationSchemaExpiresAt';
import type { NotificationSchemaLink } from './notificationSchemaLink';

export interface NotificationSchema {
  category: string;
  content: NotificationSchemaContent;
  createdAt: string;
  expiresAt: NotificationSchemaExpiresAt;
  id: number;
  isRead: boolean;
  link: NotificationSchemaLink;
  message: string;
  notificationType: string;
}
