/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewOut } from './reviewOut';

export interface PaginatedReviewSchema {
  items: ReviewOut[];
  page: number;
  size: number;
  total: number;
}
