/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunitySchema } from './communitySchema';

export interface PaginatedCommunities {
  items: CommunitySchema[];
  page: number;
  per_page: number;
  total: number;
}
