/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewSchema } from './reviewSchema';

export interface PaginatedReviewSchema {
  items: ReviewSchema[];
  page: number;
  size: number;
  total: number;
}
