/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type PostsApiListPostsParams = {
  page?: number;
  per_page?: number;
  sort_by?: string;
  sort_order?: string;
  hashtag?: string | null;
  search?: string | null;
};
