/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { PostOutId } from './postOutId';
import type { UserStats } from './userStats';

export interface PostOut {
  author: UserStats;
  comments_count?: number;
  content: string;
  created_at: string;
  hashtags?: string[];
  id?: PostOutId;
  is_author?: boolean;
  /** @maxLength 200 */
  title: string;
  upvotes?: number;
}
