/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentTypeEnum } from './contentTypeEnum';
import type { VoteEnum } from './voteEnum';

export interface ReactionIn {
  content_type: ContentTypeEnum;
  object_id: number;
  vote: VoteEnum;
}
