/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Input schema for resetting a user's password. Requires the user's email.
 */
export interface ResetPasswordSchema {
  confirm_password: string;
  password: string;
  token: string;
}
