/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { Tag } from './tag';
import type { ResolveExternalArticleSchemaPdfLink } from './resolveExternalArticleSchemaPdfLink';
import type { ExternalSource } from './externalSource';

/**
 * Metadata for an article the user read in the feed and wants to post somewhere.

The feed serves papers that may or may not already exist in our DB. `create_article`
can only create, and rejects an existing article with a bare 400 that carries no slug,
which leaves the caller unable to proceed. This schema feeds the resolve endpoint,
which returns the slug either way.
 */
export interface ResolveExternalArticleSchema {
  abstract: string;
  article_link: string;
  authors?: Tag[];
  external_id: string;
  pdf_link?: ResolveExternalArticleSchemaPdfLink;
  source: ExternalSource;
  title: string;
}
