/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewResponseSchema {
  content: string;
  created_at: string;
  id: number;
  rating: number;
  subject: string;
  updated_at: string;
}
