/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewUpdateSchema {
  content: string;
  rating: number;
  /** @maxLength 255 */
  subject: string;
}
