/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewVersionSchemaId } from './reviewVersionSchemaId';

export interface ReviewVersionSchema {
  content: string;
  created_at: string;
  id?: ReviewVersionSchemaId;
  rating: number;
  /** @maxLength 255 */
  subject: string;
  version: number;
}
