/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewSchema } from './reviewSchema';
import type { ReviewVersionSchema } from './reviewVersionSchema';

export interface ReviewWithVersionsSchema {
  review: ReviewSchema;
  versions: ReviewVersionSchema[];
}
