/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Input schema for user sign up. Requires username, first and last name,
email, password, and password confirmation.
 */
export interface SignUpSchemaIn {
  confirm_password: string;
  email: string;
  first_name: string;
  last_name: string;
  password: string;
  username: string;
}
