/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type StatusFilter = (typeof StatusFilter)[keyof typeof StatusFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusFilter = {
  submitted: 'submitted',
  approved: 'approved',
  under_review: 'under_review',
  accepted: 'accepted',
  rejected: 'rejected',
  published: 'published',
  unsubmitted: 'unsubmitted',
} as const;
