/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCommunitySchemaDescription } from './updateCommunitySchemaDescription';
import type { UpdateCommunitySchemaName } from './updateCommunitySchemaName';
import type { UpdateCommunitySchemaType } from './updateCommunitySchemaType';

export interface UpdateCommunitySchema {
  description: UpdateCommunitySchemaDescription;
  name: UpdateCommunitySchemaName;
  type: UpdateCommunitySchemaType;
}
