/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { Tag } from './tag';

export type UpdateArticleDetailsKeywords = Tag[] | null;
