/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePostSchemaCitedArticleId } from './updatePostSchemaCitedArticleId';
import type { UpdatePostSchemaCitedUrl } from './updatePostSchemaCitedUrl';
import type { UpdatePostSchemaContent } from './updatePostSchemaContent';
import type { UpdatePostSchemaTitle } from './updatePostSchemaTitle';

export interface UpdatePostSchema {
  cited_article_id?: UpdatePostSchemaCitedArticleId;
  cited_url?: UpdatePostSchemaCitedUrl;
  content?: UpdatePostSchemaContent;
  title?: UpdatePostSchemaTitle;
}
