/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { FAQSchema } from './fAQSchema';
import type { UpdateArticleDetailsAbstract } from './updateArticleDetailsAbstract';
import type { UpdateArticleDetailsAuthors } from './updateArticleDetailsAuthors';
import type { UpdateArticleDetailsSubmissionType } from './updateArticleDetailsSubmissionType';
import type { UpdateArticleDetailsTitle } from './updateArticleDetailsTitle';

export interface UpdateArticleDetails {
  abstract: UpdateArticleDetailsAbstract;
  authors: UpdateArticleDetailsAuthors;
  faqs?: FAQSchema[];
  submission_type: UpdateArticleDetailsSubmissionType;
  title: UpdateArticleDetailsTitle;
}
