/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type UsersCommonApiCheckPermissionDashboardType =
  (typeof UsersCommonApiCheckPermissionDashboardType)[keyof typeof UsersCommonApiCheckPermissionDashboardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersCommonApiCheckPermissionDashboardType = {
  article: 'article',
  community: 'community',
} as const;
