/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type UsersApiGetHashtagsParams = {
  sort?: 'popular' | 'recent' | 'alphabetical';
  search?: string;
  page?: number;
  per_page?: number;
};
