/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { UserStatsBio } from './userStatsBio';
import type { UserStatsCommunitiesJoined } from './userStatsCommunitiesJoined';
import type { UserStatsContributedArticles } from './userStatsContributedArticles';
import type { UserStatsContributedPosts } from './userStatsContributedPosts';
import type { UserStatsHomePageUrl } from './userStatsHomePageUrl';
import type { UserStatsId } from './userStatsId';
import type { UserStatsProfilePicUrl } from './userStatsProfilePicUrl';
import type { UserStatsReputationLevel } from './userStatsReputationLevel';
import type { UserStatsReputationScore } from './userStatsReputationScore';

export interface UserStats {
  bio?: UserStatsBio;
  communities_joined?: UserStatsCommunitiesJoined;
  contributed_articles?: UserStatsContributedArticles;
  contributed_posts?: UserStatsContributedPosts;
  home_page_url?: UserStatsHomePageUrl;
  id?: UserStatsId;
  profile_pic_url?: UserStatsProfilePicUrl;
  reputation_level?: UserStatsReputationLevel;
  reputation_score?: UserStatsReputationScore;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   */
  username: string;
}
