/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum for configuration value types.
 */
export type UserConfigType = (typeof UserConfigType)[keyof typeof UserConfigType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserConfigType = {
  boolean: 'boolean',
  string: 'string',
  number: 'number',
} as const;
