/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type UsersApiListMyArticlesParams = {
page?: number;
per_page?: number;
search?: string | null;
};
