/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import type { UserToJoinProfilePicUrl } from './userToJoinProfilePicUrl';

export interface UserToJoin {
  email: string;
  id: number;
  profile_pic_url: UserToJoinProfilePicUrl;
  username: string;
}
