/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export type UsersApiGetNotificationsParams = {
  /**
   * Filter by article slug
   */
  article_slug?: string | null;
  /**
   * Filter by community ID
   */
  community_id?: number | null;
  /**
   * Filter by post ID
   */
  post_id?: number | null;
};
