/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */

export interface UserPostSchema {
  action: string;
  action_date: string;
  created_at: string;
  likes_count: number;
  title: string;
}
