/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * MyApp API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  MyappUploadApiUploadImageBody,
  UploadImageResponse
} from '.././schemas'
import { customInstance } from '.././custom-instance';
import type { ErrorType, BodyType } from '.././custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * Upload an image to S3 for use in markdown editors.

**Size Limit:** 500KB

**Allowed Types:** image/jpeg, image/png, image/gif, image/webp, image/avif

**Rate Limit:** 10 uploads per minute per user

**Origin Restriction:** Only requests from scicommons.org domains are allowed.

Images are stored in `user-attachments/{env}/` with ref_count=0.
When the image is used in submitted content, ref_count is incremented.
Orphaned images (ref_count=0) can be cleaned up periodically.

**Frontend Usage:**
```javascript
const formData = new FormData();
formData.append('file', imageFile);

const response = await fetch('/api/uploads/image', {
    method: 'POST',
    headers: { 'Authorization': 'Bearer <token>' },
    body: formData
});
const { public_url } = await response.json();

// Insert into markdown editor
editor.insertText(`![image](${public_url})`);
```
 * @summary Upload an image for markdown editor
 */
export const myappUploadApiUploadImage = (
    myappUploadApiUploadImageBody: BodyType<MyappUploadApiUploadImageBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      const formData = new FormData();
formData.append('file', myappUploadApiUploadImageBody.file)

      return customInstance<UploadImageResponse>(
      {url: `/api/uploads/image`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      options);
    }
  


export const getMyappUploadApiUploadImageMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof myappUploadApiUploadImage>>, TError,{data: BodyType<MyappUploadApiUploadImageBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof myappUploadApiUploadImage>>, TError,{data: BodyType<MyappUploadApiUploadImageBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof myappUploadApiUploadImage>>, {data: BodyType<MyappUploadApiUploadImageBody>}> = (props) => {
          const {data} = props ?? {};

          return  myappUploadApiUploadImage(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MyappUploadApiUploadImageMutationResult = NonNullable<Awaited<ReturnType<typeof myappUploadApiUploadImage>>>
    export type MyappUploadApiUploadImageMutationBody = BodyType<MyappUploadApiUploadImageBody>
    export type MyappUploadApiUploadImageMutationError = ErrorType<unknown>

    /**
 * @summary Upload an image for markdown editor
 */
export const useMyappUploadApiUploadImage = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof myappUploadApiUploadImage>>, TError,{data: BodyType<MyappUploadApiUploadImageBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof myappUploadApiUploadImage>>,
        TError,
        {data: BodyType<MyappUploadApiUploadImageBody>},
        TContext
      > => {

      const mutationOptions = getMyappUploadApiUploadImageMutationOptions(options);

      return useMutation(mutationOptions);
    }
    